/**
 * AUTO-GENERATED FILE
 * Do not manually edit this file. It is generated by the `templates` package build process.
 * Based on the files present in `packages/server/templates/src/handlebars`.
 */

export const EMAIL_TEMPLATES = [
  "access-grant-created",
  "access-grant-revoked",
  "account-claim",
  "course-completed",
  "email-verification",
  "enrolment-activated",
  "enrolment-cancelled",
  "enrolment-revoked",
  "event-cancelled",
  "event-registration-confirmed",
  "event-registration-promoted",
  "event-registration-waitlisted",
  "indicator-access-granted",
  "indicator-access-revoked",
  "indicator-link-nudge",
  "invoice-issued",
  "password-changed",
  "password-reset",
  "payment-failed",
  "payment-receipt",
  "refund-approved",
  "refund-failed",
  "refund-rejected",
  "refund-succeeded",
  "registration-cancelled",
  "registration-reminder-due",
  "role-assignment-assigned",
  "role-assignment-revoked",
  "subscription-cancelled",
  "subscription-created",
  "subscription-expired",
  "subscription-past-due",
  "subscription-renewal-upcoming",
  "two-factor-disabled",
  "two-factor-enabled",
  "user-welcome"
] as const;
export type EmailTemplate = typeof EMAIL_TEMPLATES[number];

export const DOCUMENT_TEMPLATES = [
  "certificate",
  "invoice",
  "receipt"
] as const;
export type DocumentTemplate = typeof DOCUMENT_TEMPLATES[number];

export const SMS_TEMPLATES = [
  "enrolment-activated",
  "event-cancelled",
  "event-registration-confirmed",
  "password-reset",
  "payment-failed",
  "payment-receipt",
  "refund-succeeded",
  "subscription-past-due"
] as const;
export type SmsTemplate = typeof SMS_TEMPLATES[number];

export const WHATSAPP_TEMPLATES = [
  "course-completed",
  "enrolment-activated",
  "event-cancelled",
  "event-registration-confirmed",
  "payment-failed",
  "payment-receipt",
  "refund-succeeded",
  "subscription-past-due"
] as const;
export type WhatsAppTemplate = typeof WHATSAPP_TEMPLATES[number];
