import createFetchClient, { type Client, type Middleware } from 'openapi-fetch';
import type { paths } from '@workspace/client-types';
import type {
  ApiSuccessResponse,
  ApiErrorResponse,
  ApiResponseMeta,
} from '@workspace/client-types';
import { logger as defaultLogger } from '@workspace/client-lib/logger';
import { ApiError } from './errors';

// ============================================================================
// Logger interface (injected)
// ============================================================================
export interface ClientLogger {
  warn(args: { message: string; context?: Record<string, unknown>; error?: unknown }): void;
  error(args: { message: string; context?: Record<string, unknown>; error?: unknown }): void;
}

// ============================================================================
// Client Options
// ============================================================================
export interface ApiClientOptions {
  baseUrl: string;
  logger?: ClientLogger;
  fetchImpl?: typeof fetch;
  headers?: HeadersInit;
  credentials?: RequestCredentials;
}

/**
 * The fully-typed client, generated from `paths` (`@workspace/client-types`, itself
 * generated by `pnpm --filter @workspace/client-types generate-openapi` against the live
 * API). Call it exactly as documented by openapi-fetch:
 *   `client.GET('/programmes')`
 *   `client.POST('/auth/login', { body: { email, password } })`
 *   `client.GET('/cohorts', { params: { query: { programmeId } } })`
 * No hand-maintained endpoint map — every path, param, body, and response type comes
 * straight from the schema.
 */
export type ApiClient = Client<paths>;

function createLoggingMiddleware(logger?: ClientLogger): Middleware {
  return {
    async onResponse({ request, response }) {
      if (response.ok) return response;

      let details: unknown;
      try {
        details = await response.clone().json();
      } catch {
        details = await response.clone().text();
      }

      logger?.warn?.({
        message: 'API request returned error status',
        context: { method: request.method, url: request.url, status: response.status, details },
      });

      return response;
    },
  };
}

function createFetcher(options: ApiClientOptions): ApiClient {
  // Defaults to the shared @workspace/client-lib logger (redacts sensitive
  // fields, routes to console.warn/error) so every failed request — every
  // call site, not just ones that remembered to pass `logger` — surfaces its
  // real status/url/response body somewhere visible, instead of only the
  // generic message a caller's catch block chooses to show the end user.
  const { baseUrl, logger = defaultLogger, fetchImpl, headers, credentials } = options;
  const client = createFetchClient<paths>({ baseUrl, fetch: fetchImpl, headers, credentials });
  client.use(createLoggingMiddleware(logger));
  return client;
}

// ============================================================================
// createApiClient — server-only API client factory
// ============================================================================
/**
 * Every server-side caller goes through here, so this is the one place that
 * attaches `X-Origin-Auth` for apps/api's OriginAuthMiddleware — callers don't
 * each have to remember it. `ORIGIN_AUTH_SECRET` must never be read from
 * `createClientFetcher` below: that factory backs browser-side call sites, and
 * shipping this value there would put the secret in the JS bundle.
 */
export function createApiClient(options: ApiClientOptions): ApiClient {
  const originAuthSecret = process.env.ORIGIN_AUTH_SECRET?.replace(/\s+/g, '');
  return createFetcher({
    ...options,
    headers: {
      ...(originAuthSecret ? { 'X-Origin-Auth': originAuthSecret } : {}),
      ...options.headers,
    },
  });
}

// ============================================================================
// createClientFetcher — browser-safe API client factory
// ============================================================================
/**
 * Defaults `credentials: 'include'` — apps/members and apps/backoffice call the
 * API cross-origin from the browser (members.example.com/backoffice.example.com
 * -> api.example.com), and the browser only attaches cookies to a cross-origin
 * fetch when the request opts in. The cookie itself also needs a shared
 * `Domain` (see each app's shared/lib/cookies.ts, `COOKIE_DOMAIN`) — this alone
 * isn't sufficient, but is necessary.
 */
export function createClientFetcher(options: ApiClientOptions): ApiClient {
  return createFetcher({ ...options, credentials: options.credentials ?? 'include' });
}

// ============================================================================
// unwrap — reconcile openapi-fetch's typed result with the real runtime shape
// ============================================================================
/**
 * The generated schema documents each route's *inner* payload — `@nestjs/swagger`
 * reflects each controller's declared return type, not the wrapping
 * `HttpResponseEnvelopeInterceptor` adds at runtime. Every real response body is
 * actually `ApiSuccessResponse<T>` / `ApiErrorResponse` on the wire (verified against a
 * live `GET /api/v1/programmes`: `{"success":true,"statusCode":200,"data":[...],...}`),
 * even though openapi-fetch types `result.data` as the bare inner `T`.
 *
 * `unwrap` re-casts once, here, instead of at every call site: throws `ApiError` for the
 * error branch, and returns the real inner `data` + `meta` (pagination, etc.) for the
 * success branch.
 */
export interface UnwrappedResult<T> {
  data: T;
  meta?: ApiResponseMeta | null;
}

export function unwrap<T>(result: {
  data?: T;
  error?: unknown;
  response: Response;
}): UnwrappedResult<T> {
  if (result.error !== undefined) {
    const envelope = result.error as ApiErrorResponse;
    throw new ApiError(
      envelope.message ?? `Request failed (${result.response.status})`,
      result.response.status,
      result.response.url,
      envelope,
    );
  }

  if (result.data === undefined) {
    // 204 No Content — HttpResponseEnvelopeInterceptor sends no body at all.
    return { data: undefined as T, meta: undefined };
  }

  const envelope = result.data as unknown as ApiSuccessResponse<T>;
  return { data: envelope.data, meta: envelope.meta };
}
