import * as fs from 'node:fs';
import * as path from 'node:path';

// Define the absolute paths based on the script running in the templates package root
const TEMPLATES_DIR = path.join(process.cwd(), 'src/handlebars');
const CONSTANTS_OUTPUT_FILE = path.join(process.cwd(), '../constants/src/templates.ts');

function getTemplateNames(subDir: string): string[] {
  const dirPath = path.join(TEMPLATES_DIR, subDir);
  if (!fs.existsSync(dirPath)) return [];

  return fs
    .readdirSync(dirPath)
    .filter((file) => file.endsWith('.mjml') || file.endsWith('.hbs'))
    .map((file) => file.replace(/\.(mjml|hbs)$/, ''));
}

function generateConstants() {
  const emails = getTemplateNames('emails');
  const documents = getTemplateNames('documents');
  const sms = getTemplateNames('sms');
  const whatsapp = getTemplateNames('whatsapp');

  const output = `/**
 * AUTO-GENERATED FILE
 * Do not manually edit this file. It is generated by the \`templates\` package build process.
 * Based on the files present in \`packages/server/templates/src/handlebars\`.
 */

export const EMAIL_TEMPLATES = ${JSON.stringify(emails, null, 2)} as const;
export type EmailTemplate = typeof EMAIL_TEMPLATES[number];

export const DOCUMENT_TEMPLATES = ${JSON.stringify(documents, null, 2)} as const;
export type DocumentTemplate = typeof DOCUMENT_TEMPLATES[number];

export const SMS_TEMPLATES = ${JSON.stringify(sms, null, 2)} as const;
export type SmsTemplate = typeof SMS_TEMPLATES[number];

export const WHATSAPP_TEMPLATES = ${JSON.stringify(whatsapp, null, 2)} as const;
export type WhatsAppTemplate = typeof WHATSAPP_TEMPLATES[number];
`;

  fs.writeFileSync(CONSTANTS_OUTPUT_FILE, output);
  console.log('✅ Template constants successfully generated!');
}

generateConstants();
