export const AuthErrorCodes = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_TWO_FACTOR_REQUIRED: 'AUTH_TWO_FACTOR_REQUIRED',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_EMAIL_ALREADY_EXISTS: 'AUTH_EMAIL_ALREADY_EXISTS',
  AUTH_OAUTH_PROVIDER_NOT_REGISTERED: 'AUTH_OAUTH_PROVIDER_NOT_REGISTERED',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_OAUTH_EXCHANGE_FAILED: 'AUTH_OAUTH_EXCHANGE_FAILED',
  AUTH_OAUTH_ACCOUNT_NOT_LINKED: 'AUTH_OAUTH_ACCOUNT_NOT_LINKED',
  AUTH_CLAIM_TOKEN_INVALID: 'AUTH_CLAIM_TOKEN_INVALID',
  AUTH_CLAIM_TOKEN_EXPIRED: 'AUTH_CLAIM_TOKEN_EXPIRED',
  AUTH_CLAIM_ALREADY_CLAIMED: 'AUTH_CLAIM_ALREADY_CLAIMED',
  AUTH_TURNSTILE_VERIFICATION_FAILED: 'AUTH_TURNSTILE_VERIFICATION_FAILED',
  AUTH_EMAIL_VERIFICATION_TOKEN_INVALID: 'AUTH_EMAIL_VERIFICATION_TOKEN_INVALID',
  AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED: 'AUTH_EMAIL_VERIFICATION_TOKEN_EXPIRED',
  AUTH_EMAIL_ALREADY_VERIFIED: 'AUTH_EMAIL_ALREADY_VERIFIED',
} as const;

export type AuthErrorCode = (typeof AuthErrorCodes)[keyof typeof AuthErrorCodes];
