export const IdentityErrorCodes = {
  IDENTITY_ROLE_NOT_FOUND: 'IDENTITY_ROLE_NOT_FOUND',
  IDENTITY_ROLE_ALREADY_EXISTS: 'IDENTITY_ROLE_ALREADY_EXISTS',
  IDENTITY_PERMISSION_NOT_FOUND: 'IDENTITY_PERMISSION_NOT_FOUND',
  IDENTITY_PERMISSION_ALREADY_EXISTS: 'IDENTITY_PERMISSION_ALREADY_EXISTS',
  IDENTITY_ROLE_ALREADY_ASSIGNED: 'IDENTITY_ROLE_ALREADY_ASSIGNED',
  IDENTITY_ROLE_ASSIGNMENT_NOT_FOUND: 'IDENTITY_ROLE_ASSIGNMENT_NOT_FOUND',
  IDENTITY_API_CLIENT_NOT_FOUND: 'IDENTITY_API_CLIENT_NOT_FOUND',
  IDENTITY_API_CLIENT_ALREADY_EXISTS: 'IDENTITY_API_CLIENT_ALREADY_EXISTS',
  IDENTITY_API_CLIENT_NOT_ACTIVE: 'IDENTITY_API_CLIENT_NOT_ACTIVE',
  IDENTITY_API_KEY_NOT_FOUND: 'IDENTITY_API_KEY_NOT_FOUND',
  IDENTITY_API_KEY_REVOKED_OR_EXPIRED: 'IDENTITY_API_KEY_REVOKED_OR_EXPIRED',
  IDENTITY_PERMISSION_DENIED: 'IDENTITY_PERMISSION_DENIED',
} as const;

export type IdentityErrorCode = (typeof IdentityErrorCodes)[keyof typeof IdentityErrorCodes];
