export const VALIDATED_ENV_TOKEN = Symbol('VALIDATED_ENV_TOKEN');
export const APP_RUNTIME_CONFIG_TOKEN = Symbol('APP_RUNTIME_CONFIG_TOKEN');
export const HTTP_RUNTIME_CONFIG_TOKEN = Symbol('HTTP_RUNTIME_CONFIG_TOKEN');
export const CONTEXT_RUNTIME_CONFIG_TOKEN = Symbol('CONTEXT_RUNTIME_CONFIG_TOKEN');
export const PERSISTENCE_RUNTIME_CONFIG_TOKEN = Symbol('PERSISTENCE_RUNTIME_CONFIG_TOKEN');
export const MONGO_RUNTIME_CONFIG_TOKEN = Symbol('MONGO_RUNTIME_CONFIG_TOKEN');
export const PRISMA_RUNTIME_CONFIG_TOKEN = Symbol('PRISMA_RUNTIME_CONFIG_TOKEN');
export const REDIS_RUNTIME_CONFIG_TOKEN = Symbol('REDIS_RUNTIME_CONFIG_TOKEN');
export const AUTH_RUNTIME_CONFIG_TOKEN = Symbol('AUTH_RUNTIME_CONFIG_TOKEN');
export const GOOGLE_OAUTH_RUNTIME_CONFIG_TOKEN = Symbol('GOOGLE_OAUTH_RUNTIME_CONFIG_TOKEN');
export const GITHUB_OAUTH_RUNTIME_CONFIG_TOKEN = Symbol('GITHUB_OAUTH_RUNTIME_CONFIG_TOKEN');
export const OBSERVABILITY_RUNTIME_CONFIG_TOKEN = Symbol('OBSERVABILITY_RUNTIME_CONFIG_TOKEN');
export const STORAGE_RUNTIME_CONFIG_TOKEN = Symbol('STORAGE_RUNTIME_CONFIG_TOKEN');
export const BRANDING_RUNTIME_CONFIG_TOKEN = Symbol('BRANDING_RUNTIME_CONFIG_TOKEN');
export const CORS_RUNTIME_CONFIG_TOKEN = Symbol('CORS_RUNTIME_CONFIG_TOKEN');
export const EMAIL_RUNTIME_CONFIG_TOKEN = Symbol('EMAIL_RUNTIME_CONFIG_TOKEN');
export const WHATSAPP_RUNTIME_CONFIG_TOKEN = Symbol('WHATSAPP_RUNTIME_CONFIG_TOKEN');
export const SMS_RUNTIME_CONFIG_TOKEN = Symbol('SMS_RUNTIME_CONFIG_TOKEN');
export const PUSH_RUNTIME_CONFIG_TOKEN = Symbol('PUSH_RUNTIME_CONFIG_TOKEN');
export const PAYMENT_PROVIDERS_RUNTIME_CONFIG_TOKEN = Symbol(
  'PAYMENT_PROVIDERS_RUNTIME_CONFIG_TOKEN',
);
export const ENCRYPTION_RUNTIME_CONFIG_TOKEN = Symbol('ENCRYPTION_RUNTIME_CONFIG_TOKEN');
export const CAPTCHA_RUNTIME_CONFIG_TOKEN = Symbol('CAPTCHA_RUNTIME_CONFIG_TOKEN');
