export const PAYMENT_GATEWAY_TOKEN = Symbol('PAYMENT_GATEWAY_TOKEN');
export const PAYSTACK_GATEWAY_TOKEN = Symbol('PAYSTACK_GATEWAY_TOKEN');
export const FLUTTERWAVE_GATEWAY_TOKEN = Symbol('FLUTTERWAVE_GATEWAY_TOKEN');
export const PAYMENTS_APP_TOKEN = Symbol('PAYMENTS_APP_TOKEN');
