import {
  OutboxEventStatus,
  DLQEventStatus,
  SagaStatus,
  IdempotencyStatus,
} from '@workspace/constants';
import { DatabaseTx } from '../shared';
import { RepoQueryOptions } from '../types';

// ─────────────────────────────────────────────────────────────────────────────
// OutboxEvent Types
// ─────────────────────────────────────────────────────────────────────────────
export interface OutboxEventPersistence {
  id: string;

  aggregateType: string;
  aggregateId: string;
  eventType: string;
  eventVersion: number;
  payload: Record<string, unknown>;
  metadata: Record<string, unknown> | null;
  correlationId: string | null;
  maxAttempts: number;
  status: OutboxEventStatus | 'PENDING' | 'PROCESSING' | 'PROCESSED' | 'FAILED' | 'DEAD_LETTERED';
  publishedAt: Date | null;
  attempts: number;
  lastAttemptAt: Date | null;
  nextRetryAt: Date | null;
  lastError: string | null;
  partitionKey: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateOutboxEventInput extends Omit<
  OutboxEventPersistence,
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'status'
  | 'attempts'
  | 'lastAttemptAt'
  | 'nextRetryAt'
  | 'lastError'
  | 'publishedAt'
  | 'payload'
  | 'metadata'
> {
  id?: string; // Optional, can be generated by repo
  status?: OutboxEventPersistence['status'];
  payload: unknown;
  metadata: unknown | null;
}

export type UpdateOutboxEventInput = Partial<
  Pick<
    OutboxEventPersistence,
    'status' | 'publishedAt' | 'attempts' | 'lastAttemptAt' | 'nextRetryAt' | 'lastError'
  >
>;

// ─────────────────────────────────────────────────────────────────────────────
// DeadLetterEvent Types
// ─────────────────────────────────────────────────────────────────────────────
export interface DeadLetterEventPersistence {
  id: string;

  source: string;
  originalEventId: string | null;
  eventType: string;
  payload: Record<string, unknown>;
  errorMessage: string;
  errorStack: string | null;
  attempts: number;
  status: DLQEventStatus | 'PENDING' | 'REPROCESSING' | 'RESOLVED' | 'ABANDONED';
  resolvedAt: Date | null;
  resolvedBy: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateDeadLetterEventInput extends Omit<
  DeadLetterEventPersistence,
  'id' | 'createdAt' | 'updatedAt' | 'status' | 'attempts' | 'resolvedAt' | 'resolvedBy'
> {
  id?: string;
}

export type UpdateDeadLetterEventInput = Partial<
  Pick<
    DeadLetterEventPersistence,
    'status' | 'attempts' | 'resolvedAt' | 'resolvedBy' | 'errorStack' | 'errorMessage'
  >
>;

// ─────────────────────────────────────────────────────────────────────────────
// SagaState Types
// ─────────────────────────────────────────────────────────────────────────────
export interface SagaStatePersistence {
  id: string;

  sagaType: string;
  correlationId: string;
  currentStep: string;
  status: SagaStatus;
  data: Record<string, unknown>;
  completedSteps: string[];
  failedStep: string | null;
  lastError: string | null;
  startedAt: Date;
  completedAt: Date | null;
  timeoutAt: Date | null;
  attempts: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface CreateSagaStateInput extends Omit<
  SagaStatePersistence,
  | 'id'
  | 'createdAt'
  | 'updatedAt'
  | 'startedAt'
  | 'completedAt'
  | 'attempts'
  | 'completedSteps'
  | 'failedStep'
  | 'lastError'
> {
  id?: string;
  completedSteps?: string[];
  completedAt?: Date | null;
  failedStep?: string | null;
  lastError?: string | null;
}

export type UpdateSagaStateInput = Partial<
  Pick<
    SagaStatePersistence,
    | 'currentStep'
    | 'status'
    | 'data'
    | 'completedSteps'
    | 'failedStep'
    | 'lastError'
    | 'completedAt'
    | 'timeoutAt'
    | 'attempts'
  >
>;

// ─────────────────────────────────────────────────────────────────────────────
// IdempotencyKey Types
// ─────────────────────────────────────────────────────────────────────────────
export interface IdempotencyKeyPersistence {
  id: string;

  key: string;
  scope: string;
  status: IdempotencyStatus;
  requestHash: string | null;
  responsePayload: Record<string, unknown> | null;
  statusCode: number | null;
  expiresAt: Date;
  completedAt: Date | null;
  createdAt: Date;
  updatedAt: Date;
}

export type IdempotencyDecision =
  | { decision: 'EXECUTE' }
  | { decision: 'SKIP'; responseData?: unknown; statusCode?: number };

export interface CreateIdempotencyKeyInput extends Omit<
  IdempotencyKeyPersistence,
  'id' | 'createdAt' | 'updatedAt' | 'completedAt' | 'status' | 'responsePayload' | 'statusCode'
> {
  id?: string;
  statusCode?: number;
  responsePayload?: Record<string, unknown> | null;
  status?: IdempotencyKeyPersistence['status'];
}

export type UpdateIdempotencyKeyInput = Partial<
  Pick<IdempotencyKeyPersistence, 'status' | 'responsePayload' | 'statusCode' | 'completedAt'>
>;

export interface SagaContext {
  sagaId: string;
  correlationId: string;
  tenantId?: string | null;
  data: Record<string, unknown>;
}

export interface SagaStep {
  name: string;
  execute(tx: DatabaseTx, context: SagaContext): Promise<void>;
  compensate?(context: SagaContext): Promise<void>;
}

export interface SagaDefinition {
  name: string;
  steps: SagaStep[];
  validate?: (data: Record<string, unknown>) => void;
  timeoutMinutes?: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// Query Options
// ─────────────────────────────────────────────────────────────────────────────
export type OutboxEventPersistenceQueryOptions<K extends keyof OutboxEventPersistence> =
  RepoQueryOptions<OutboxEventPersistence, K>;

export type DeadLetterEventPersistenceQueryOptions<K extends keyof DeadLetterEventPersistence> =
  RepoQueryOptions<DeadLetterEventPersistence, K>;

export type SagaStatePersistenceQueryOptions<K extends keyof SagaStatePersistence> =
  RepoQueryOptions<SagaStatePersistence, K>;

export type IdempotencyKeyPersistenceQueryOptions<K extends keyof IdempotencyKeyPersistence> =
  RepoQueryOptions<IdempotencyKeyPersistence, K>;
